export const IPC = {
  runtimeGetStatus: "runtime:get-status",
  runtimeGetModels: "runtime:get-models",
  projectsList: "projects:list",
  projectsCreate: "projects:create",
  projectsDelete: "projects:delete",
  projectsOpen: "projects:open",
  notesList: "notes:list",
  notesCreate: "notes:create",
  notesUpdate: "notes:update",
  notesDelete: "notes:delete",
  importPickDocx: "import:pick-docx",
  importDocx: "import:docx",
  importManualSplit: "import:manual-split",
  versionsList: "versions:list",
  chaptersList: "chapters:list",
  reviewStart: "review:start",
  reviewRunsList: "review-runs:list",
  reviewRunDelete: "review-run:delete",
  reviewRunsDeleteByStatus: "review-runs:delete-by-status",
  findingsList: "findings:list",
  findingsExport: "findings:export",
  findingUpdateStatus: "finding:update-status",
  compareVersions: "compare:versions"
} as const;
